### ISSUE TITLE
Version 2.11.1+ broke auto-generated update mutations

### ISSUE THREAD

**Issue by pkprosol** [neo4j-graphql/neo4j-graphql-js#401] opened 2020-03-04 22:20 UTC
Upon upgrading to version 2.11.1+ from 2.11.0 all of our auto-generated update mutations began returning null and not performing the update, using the same input variables and mutation structure. For example:

```
mutation ($id: ID!, $firstName: String, $lastName: String) {
      transcendental: UpdatePerson(
        id: $id,
        firstName: $firstName,
        lastName: $lastName
      )
      {
        id
        firstName
        lastName
      }
    }
```

This type of query began returning null. We still see its API in the the schema, however.

**Comment by Phylodome** [comment] 2020-03-04 23:44
Seeing this as well. Not sure if this is related, but it looks like `@relation`-annotated schema `OBJECT`s of the form:

`_Update[@relation-derived name combination]Payload`

are no longer generated once one upgrades to `^12.x.x`.

Nothing else in the codebase concerning these updates has changed, and I'm not getting any errors. 

The update just executes and returns `null`. For example:
```
{
  "data": {
    "UpdateAutomobile": null
  }
}
```

**Comment by Phylodome** [comment] 2020-03-05 00:48
After looking into this a bit more, I tracked the break back to `2.11.1` (we were upgrading from `2.10.2`).

Looking at the Changelog, nothing immediately jumps out, but I'm not that familiar with the internals of the schema augmentation.

That said, here's an example of a schema definition for which the generated `Update` query no longer works:

```
type Transcendental implements LabeledEntity {
  id: ID!
  name: String!
  description: String!
  uploads: [Upload!]! @relation(name: "HAS_IMAGE_FILE", direction: "OUT")
  capacities: [Capacity!]! @relation(name: "HAS_CAPACITY", direction: "OUT")
  landscapeTemplates: [LandscapeTemplate!]! @relation(name: "TARGETS", direction: "IN")
  contentStatus: ContentStatus!
}
```

Any ideas on why that PR might have broken these updates @michaeldgraham ?

**Comment by Phylodome** [comment] 2020-03-05 01:18
Another data point: if I remove the interface implementation, I can once again use the generated Updates.

So, something about the behavior / side effects of the interface updates in #365, shipped as `2.11.1`, seems to have broken the generated Update resolvers.

**Comment by johnymontana** [comment] 2020-03-08 01:07
@Phylodome @pkprosol Could you give the latest release v2.13.0 a try? We've significantly changed the handling of interface types in this release and I'm hoping it addresses your regressions.

**Comment by Phylodome** [comment] 2020-04-04 19:10
@johnymontana, `2.13.0` appears to fix this, though also introduces an issue where nested filters no longer appear to work properly with respect to interfaces.

For example, if I used the concrete type for a property in my Schema, I can use that property's generated `Filter` type as expected, but if I refer to the type by interface, the filter no longer works.

e.g. given:
```
type Person implements SentientBeing {
  id: ID!
  email: String!
}

type Ship {
  id: ID!
  name: String!
  captain: SentientBeing! @relation(name: "PILOTS", direction: "IN")
}
```

This query will not return any Ships.
```
query GetShipsByCaptainEmail (
  $email: String!
) {
  Ships(filter: { captain: { email: $email } }) {
    id
  }}
```

But if, in the schema, one changes the value of `Ship.captain` from `SentientBeing!` to `Person!`, the query will return the expected `Ships`.

**Comment by johnymontana** [comment] 2020-07-08 22:11
@Phylodome Closing this one as the issue you mention in your above comment is being tracked in #409

**Closed by johnymontana** 2020-07-08 22:11 UTC
