### ISSUE TITLE
[BUG] Nested ordering errors

### ISSUE THREAD

**Issue by Crodaycat** [neo4j-graphql/neo4j-graphql-js#272] opened 2019-07-07 18:51 UTC
When i try to order the values of a related entity it throws an error:

```
query {
  Chat {
    id
    messages(orderBy: [sentAt_desc]) {
      text
      sentAt {
        year
        month
        day
      }
      sender {
        id
        name
      }
    }
  }
}
```

Get this error:
```
Failed to invoke function `apoc.coll.sortMulti`: Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.Comparable
```

We are using:

- **apollo-server:** 2.6.4
- **neo4j-driver:** 1.7.4
- **neo4j-graphql-js:** 2.6.3

**Comment by johnymontana** [comment] 2019-07-10 16:39
Could you share your GraphQL type definitions so I can try to reproduce? (or at least the Chat and message types).

I'm assuming `sentAt` is a `Date` type?

**Comment by Crodaycat** [comment] 2019-07-13 19:02
`sentAt` is a `DateTime` type, here are the types definitios for Chat and Message:

```
type Chat {
  id: String!
  checkIn: DateTime
  checkOut: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!
  roomNumber: Int!
  owner: User! @relation(name: "OWNS", direction: "IN")
  messages: [Message] @relation(name: "BELONGS_TO", direction: "IN")
  hotel: Hotel @relation(name: "BELONGS_TO", direction: "OUT")
}

type Message {
  id: String!
  text: String!
  sentAt: DateTime!
  sender: User! @relation(name: "SENT", direction: "IN")
  chat: Chat! @relation(name: "BELONGS_TO", direction: "OUT")
}
```

**Comment by andrashee** [comment] 2019-08-30 09:01
I'm facing the same problem with a DateTime field. Any news on this?

**Comment by mattwr18** [comment] 2019-09-14 08:50
Hey, we are also dealing with this issue. We would like to refactor our code base to use Temporal values like `DateTime`, but ran into an issue when we try to use `orderBy: createdAt_asc` for nested attributes like `comments` on a `Post` 
```
Post(id: "p15") {
  comments(orderBy: createdAt_asc) {
    content
    createdAt {
      formatted
    }
  }
}
```
In our case, the `neo4j-graphql-js` generated query look like this
```
MATCH (`post`:`Post` {id:$id, deleted:$deleted, disabled:$disabled}) WITH `post` ORDER BY post.createdAt DESC RETURN `post` { .deleted , .disabled , .id , .id , .title , .content , .contentExcerpt ,createdAt: { formatted: toString(`post`.createdAt) }, .disabled , .deleted , .slug , .image ,author: head([(`post`)<-[:`WROTE`]-(`post_author`:`User`) | post_author { .id , .slug , .name , .avatar , .disabled , .deleted ,shoutedCount: apoc.cypher.runFirstColumn("MATCH (this)-[: SHOUTED]->(r: Post) WHERE NOT r.deleted = true AND NOT r.disabled = true RETURN COUNT(DISTINCT r)", {this: post_author, cypherParams: $cypherParams}, false),contributionsCount: apoc.cypher.runFirstColumn("MATCH (this)-[: WROTE]->(r: Post)
WHERE NOT r.deleted = true AND NOT r.disabled = true
RETURN COUNT(r)", {this: post_author, cypherParams: $cypherParams}, false),commentedCount: apoc.cypher.runFirstColumn("MATCH (this)-[: WROTE]->(: Comment)-[: COMMENTS]->(p: Post) WHERE NOT p.deleted = true AND NOT p.disabled = true RETURN COUNT(DISTINCT(p))", {this: post_author, cypherParams: $cypherParams}, false),followedByCount: apoc.cypher.runFirstColumn("MATCH (this)<-[: FOLLOWS]-(r: User) RETURN COUNT(DISTINCT r)", {this: post_author, cypherParams: $cypherParams}, false),followedByCurrentUser: apoc.cypher.runFirstColumn("MATCH (this)<-[: FOLLOWS]-(u: User { id: $cypherParams.currentUserId})
RETURN COUNT(u) >= 1", {this: post_author, cypherParams: $cypherParams}, false),location: head([ post_author_location IN apoc.cypher.runFirstColumn("MATCH (this)-[: IS_IN]->(l: Location) RETURN l", {this: post_author, cypherParams: $cypherParams}, true) | post_author_location { .nameEN }]) ,badges: [(`post_author`)<-[:`REWARDED`]-(`post_author_badges`:`Badge`) | post_author_badges { .id , .icon }] }]) ,tags: [(`post`)-[:`TAGGED`]->(`post_tags`:`Tag`) | post_tags { .id }] ,categories: [(`post`)-[:`CATEGORIZED`]->(`post_categories`:`Category`) | post_categories { .id , .name , .icon }] ,commentsCount: apoc.cypher.runFirstColumn("MATCH (this)<-[: COMMENTS]-(r: Comment) WHERE NOT r.deleted = true AND NOT r.disabled = true RETURN COUNT(DISTINCT r)", {this: post, cypherParams: $cypherParams}, false),shoutedCount: apoc.cypher.runFirstColumn("MATCH (this)<-[: SHOUTED]-(r: User) WHERE NOT r.deleted = true AND NOT r.disabled = true RETURN COUNT(DISTINCT r)", {this: post, cypherParams: $cypherParams}, false),shoutedByCurrentUser: apoc.cypher.runFirstColumn("MATCH (this)<-[: SHOUTED]-(u: User { id: $cypherParams.currentUserId}) RETURN COUNT(u) >= 1", {this: post, cypherParams: $cypherParams}, false),emotionsCount: apoc.cypher.runFirstColumn("MATCH (this)<-[emoted: EMOTED]-(: User) RETURN COUNT(DISTINCT emoted)", {this: post, cypherParams: $cypherParams}, false),comments: [sortedElement IN apoc.coll.sortMulti([(`post`)<-[:`COMMENTS`]-(`post_comments`:`Comment`) | post_comments { .deleted , .disabled , .id , .id ,createdAt: `post_comments`.createdAt, .disabled , .deleted , .content , .contentExcerpt ,author: head([(`post_comments`)<-[:`WROTE`]-(`post_comments_author`:`User`) | post_comments_author { .id , .slug , .name , .avatar , .disabled , .deleted ,shoutedCount: apoc.cypher.runFirstColumn("MATCH (this)-[: SHOUTED]->(r: Post) WHERE NOT r.deleted = true AND NOT r.disabled = true RETURN COUNT(DISTINCT r)", {this: post_comments_author, cypherParams: $cypherParams}, false),contributionsCount: apoc.cypher.runFirstColumn("MATCH (this)-[: WROTE]->(r: Post)
WHERE NOT r.deleted = true AND NOT r.disabled = true
RETURN COUNT(r)", {this: post_comments_author, cypherParams: $cypherParams}, false),commentedCount: apoc.cypher.runFirstColumn("MATCH (this)-[: WROTE]->(: Comment)-[: COMMENTS]->(p: Post) WHERE NOT p.deleted = true AND NOT p.disabled = true RETURN COUNT(DISTINCT(p))", {this: post_comments_author, cypherParams: $cypherParams}, false),followedByCount: apoc.cypher.runFirstColumn("MATCH (this)<-[: FOLLOWS]-(r: User) RETURN COUNT(DISTINCT r)", {this: post_comments_author, cypherParams: $cypherParams}, false),followedByCurrentUser: apoc.cypher.runFirstColumn("MATCH (this)<-[: FOLLOWS]-(u: User { id: $cypherParams.currentUserId})
RETURN COUNT(u) >= 1", {this: post_comments_author, cypherParams: $cypherParams}, false),location: head([ post_comments_author_location IN apoc.cypher.runFirstColumn("MATCH (this)-[: IS_IN]->(l: Location) RETURN l", {this: post_comments_author, cypherParams: $cypherParams}, true) | post_comments_author_location { .nameEN }]) ,badges: [(`post_comments_author`)<-[:`REWARDED`]-(`post_comments_author_badges`:`Badge`) | post_comments_author_badges { .id , .icon }] }]) }], ['^createdAt']) | sortedElement { .*,  }] } AS `post`
```
and the error thrown in the console is 
```
Error GraphQL error: Invalid input '}': expected whitespace, comment, literal entry, property selector, variable selector or all properties selector (line 7, column 512 (offset: 4643))
"RETURN COUNT(u) >= 1", {this: post_comments_author, cypherParams: $cypherParams}, false),location: head([ post_comments_author_location IN apoc.cypher.runFirstColumn("MATCH (this)-[: IS_IN]->(l: Location) RETURN l", {this: post_comments_author, cypherParams: $cypherParams}, true) | post_comments_author_location { .nameEN }]) ,badges: [(`post_comments_author`)<-[:`REWARDED`]-(`post_comments_author_badges`:`Badge`) | post_comments_author_badges { .id , .icon }] }]) }], ['^createdAt']) | 
sortedElement { .*,  }] } AS `post`"
                     ^
```

Here is our `Post` and `Comment` schema in case it's helpful for anyone
```
type Post {
  id: ID!
  activityId: String
  objectId: String
  author: User @relation(name: "WROTE", direction: "IN")
  title: String!
  slug: String
  content: String!
  contentExcerpt: String
  image: String
  imageUpload: Upload
  visibility: Visibility
  deleted: Boolean
  disabled: Boolean
  disabledBy: User @relation(name: "DISABLED", direction: "IN")
  createdAt: DateTime
  updatedAt: String
  language: String
  relatedContributions: [Post]!
  @cypher(
  statement: """
  MATCH (this)-[: TAGGED|CATEGORIZED]->(categoryOrTag)<-[: TAGGED|CATEGORIZED]-(post: 
  Post)
  WHERE NOT post.deleted AND NOT post.disabled
  RETURN DISTINCT post
  LIMIT 10
  """
  )

  tags: [Tag]! @relation(name: "TAGGED", direction: "OUT")
  categories: [Category]! @relation(name: "CATEGORIZED", direction: "OUT")

  comments: [Comment]! @relation(name: "COMMENTS", direction: "IN")
  commentsCount: Int!
  @cypher(
  statement: "MATCH (this)<-[: COMMENTS]-(r: Comment) WHERE NOT r.deleted = true AND NOT 
  r.disabled = true RETURN COUNT(DISTINCT r)"
  )

  shoutedBy: [User]! @relation(name: "SHOUTED", direction: "IN")
  shoutedCount: Int!
  @cypher(
  statement: "MATCH (this)<-[: SHOUTED]-(r: User) WHERE NOT r.deleted = true AND NOT 
  r.disabled = true RETURN COUNT(DISTINCT r)"
  )

  # Has the currently logged in user shouted that post?
  shoutedByCurrentUser: Boolean!
  @cypher(
  statement: "MATCH (this)<-[: SHOUTED]-(u: User { id: $cypherParams.currentUserId}) RETURN 
  COUNT(u) >= 1"
  )

  emotions: [EMOTED]
  emotionsCount: Int!
  @cypher(statement: "MATCH (this)<-[emoted: EMOTED]-(: User) RETURN COUNT(DISTINCT 
  emoted)")
}

input _PostInput {
  id: ID!
}

type Mutation {
  CreatePost(
  id: ID
  title: String!
  slug: String
  content: String!
  image: String
  imageUpload: Upload
  visibility: Visibility
  language: String
  categoryIds: [ID]
  contentExcerpt: String
  ): Post
  UpdatePost(
  id: ID!
  title: String!
  slug: String
  content: String!
  contentExcerpt: String
  image: String
  imageUpload: Upload
  visibility: Visibility
  language: String
  categoryIds: [ID]
  ): Post
  DeletePost(id: ID!): Post
  AddPostEmotions(to: _PostInput!, data: _EMOTEDInput!): EMOTED
  RemovePostEmotions(to: _PostInput!, data: _EMOTEDInput!): EMOTED
}
type Query {
  PostsEmotionsCountByEmotion(postId: ID!, data: _EMOTEDInput!): Int!
  PostsEmotionsByCurrentUser(postId: ID!): [String]
}
```
```
type Comment {
  id: ID!
  activityId: String
  author: User @relation(name: "WROTE", direction: "IN")
  content: String!
  contentExcerpt: String
  post: Post @relation(name: "COMMENTS", direction: "OUT")
  createdAt: DateTime
  updatedAt: String
  deleted: Boolean
  disabled: Boolean
  disabledBy: User @relation(name: "DISABLED", direction: "IN")
}

type Mutation {
  CreateComment(
  id: ID
  postId: ID!
  content: String!
  contentExcerpt: String
  deleted: Boolean
  disabled: Boolean
  ): Comment
  UpdateComment(
  id: ID!
  content: String!
  contentExcerpt: String
  deleted: Boolean
  disabled: Boolean
  ): Comment
  DeleteComment(id: ID!): Comment
}
```

Wanna say a big thank you to @johnymontana and the other contributors to this library.
Maybe, we can help come to a solution for this issue.

**Comment by g3rd** [comment] 2019-11-01 21:38
Has anyone found a workaround or fix for this issue?

**Comment by johnymontana** [comment] 2019-11-03 14:10
Thanks for pinging this @g3rd  - will try to address it this week.

I suppose a temporary workaround might be to store an additional property that is the epoch milliseconds version of the timestamp as a Long and use that for ordering instead of the DateTime field?

**Comment by debugpoint136** [comment] 2019-11-17 17:12
I am facing the same problem on spatial `Point` as well.

**Comment by mobsean** [comment] 2020-02-19 10:45
> Thanks for pinging this @g3rd - will try to address it this week.
> 
> I suppose a temporary workaround might be to store an additional property that is the epoch milliseconds version of the timestamp as a Long and use that for ordering instead of the DateTime field?

The proposed workaround works! Thanks!

**Closed** 2020-07-24 20:44 UTC
Labels: Priority Bug Fix

**Comment by loicmarie** [comment] 2020-09-22 10:50
This issue still occurs in 2.16.3 with nested requests such as:
```gql
query ($id: ID!, $first: Int!, $offset: Int!) {
  User(id: $id) {
    posts(first: $first, offset: $offset, orderBy: createdAt_desc) {
      id
    }
  }
}
```

**Comment by WTX1** [comment] 2020-10-03 01:04
> This issue still occurs in 2.16.3 with nested requests such as:
> 
> ```graphql
> query ($id: ID!, $first: Int!, $offset: Int!) {
>   User(id: $id) {
>     posts(first: $first, offset: $offset, orderBy: createdAt_desc) {
>       id
>     }
>   }
> }
> ```

Hi
Make sure you have installed the APOC library first 

You can follow the instructions here : https://neo4j.com/labs/apoc/4.1/installation/

**Comment by Kubera2017** [comment] 2020-10-21 18:05
I installed https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.1.0.2 the issue persists

**Comment by erik7z** [comment] 2021-02-24 14:56
Sorting by date works when you requesting it only from one entity:
`
query {
  Question {
    nodeId
    comments(orderBy: createdAt_asc) {
      nodeId
      text
    }
  }
}
`

But if you requesting it on more entities, than it fails:

`
query {
  Question {
    nodeId
    comments(orderBy: createdAt_asc) {
      nodeId
      text
    }
    answers(orderBy: createdAt_asc) {
      nodeId
      text
    }
  }
}
`
and gives following error:
`Neo4jError: Failed to invoke function `apoc.coll.sortMulti`: Caused by: java.lang.ClassCastException: class java.util.HashMap cannot be cast to class java.lang.Comparable (java.util.HashMap and java.lang.Comparable are in module java.base of loader 'bootstrap')`
